baseurl      = "https://juliopdx.com/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "../docs"
enableEmoji  = false

[permalinks]
  posts = '/:year/:month/:day/:title/'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Thank you for stopping by!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Theme toggle
  enableThemeToggle = true

  [params.footer]
    trademark = true
    rss = true
    copyright = false
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/Julio_PDX"

  [[params.social]]
    name = "github"
    url  = "https://github.com/JulioPDX"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/julioperez-pdx/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
    author = "authors"

[languages]
  [languages.en]
    title = "Welcome to the World of Tomorrow"
    subtitle = "Welcome to my blog!"
    keywords = ""
    #copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "JulioPDX"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"