Laptop: {
  VS Code Install
  VS Code Browser
}

Laptop <-> Azure Cloud
Azure Cloud.Virtual Machine.Container
Azure Cloud.Virtual Machine.Container: {
  style: {
    stroke: red
  }
  Repository
  Languages
  Tooling
}
Azure Cloud.Virtual Machine: {
  CPU
  Disk
}