direction: right
nats server -> runner 1
nats server -> runner 2
nats server -> runner 3
runner 1 -> spine1: dc1.spine1.configure
runner 2 -> leaf1: dc1.leaf1.configure
runner 3 -> leaf2: dc1.leaf2.configure